/*
* Generated file
*
* Generated from: yang module name: negotiator-impl yang module local name: negotiator-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jul 17 10:39:18 BST 2017
*
* Do not modify this file unless it is present under src/main directory
*/
package eu.virtuwind.negotiator.impl;
public interface NegotiatorModuleMXBean {
    public javax.management.ObjectName getRpcRegistry();

    public void setRpcRegistry(javax.management.ObjectName rpcRegistry);

    public javax.management.ObjectName getDataBroker();

    public void setDataBroker(javax.management.ObjectName dataBroker);

    public javax.management.ObjectName getNotificationService();

    public void setNotificationService(javax.management.ObjectName notificationService);

}
